/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cesar.renda.view;

import com.cesar.utils.SwingUtils;
import javax.swing.JScrollPane;

/**
 *
 * @author cesar
 */
public class Renda extends javax.swing.JFrame {
    JScrollPane scrollContainer = new JScrollPane();
    
    /**
     * Creates new form Renda
     */
    public Renda() {
        initComponents();
//        SwingUtils.addInternalFrame(desktop, new Dashboard());
    }
//
//    private void configDesktop(){
//        scrollContainer.setOpaque(false);
//        scrollContainer.setViewportView(desktop);
//        addComponentListener(new ComponentAdapter() {
//            @Override
//            public void componentResized(ComponentEvent evt) {
//                revalidateDesktopPane();
//            }
//        });
//    }
//    
//    private void revalidateDesktopPane() {
//        Dimension dim = new Dimension(0,0);
//        Component[] com = desktop.getComponents();
//        for (int i=0 ; i<com.length ; i++) {
//            int w = (int) dim.getWidth()+com[i].getWidth();
//            int h = (int) dim.getHeight()+com[i].getHeight();
//            dim.setSize(new Dimension(w,h));
//        }
//        desktop.setPreferredSize(dim);
//        desktop.revalidate();
//        revalidate();
//        repaint();  
//    }
//    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuDashboard = new javax.swing.JMenuItem();
        menuApartamento = new javax.swing.JMenu();
        menuItemNovoApartamento = new javax.swing.JMenuItem();
        menuItemVerApartamento = new javax.swing.JMenuItem();
        menuInquilino = new javax.swing.JMenu();
        menuItemNovoInquilino = new javax.swing.JMenuItem();
        menuItemVerInquilino = new javax.swing.JMenuItem();
        menuPagamento = new javax.swing.JMenu();
        menuItemNovoPagamento = new javax.swing.JMenuItem();
        menuItemVerPagamento = new javax.swing.JMenuItem();
        menuSenhorio = new javax.swing.JMenu();
        menuItemNovoSenhorio = new javax.swing.JMenuItem();
        menuItemVerSenhorio = new javax.swing.JMenuItem();
        menuUtilizador = new javax.swing.JMenu();
        menuItemNovoUtilizador = new javax.swing.JMenuItem();
        menuItemVerUtilizador = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão de Renda");
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

        desktop.setAutoscrolls(true);

        jLabel5.setFont(new java.awt.Font("FZKai-Z03", 0, 150)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(93, 109, 115));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("S G R");

        desktop.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addContainerGap())
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/menu_24.png"))); // NOI18N
        menu.setText("Menu");
        menu.setMargin(new java.awt.Insets(0, 5, 0, 0));

        menuDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/chart_16.png"))); // NOI18N
        menuDashboard.setText("DashBoard");
        menuDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDashboardActionPerformed(evt);
            }
        });
        menu.add(menuDashboard);

        menuApartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/home_16.png"))); // NOI18N
        menuApartamento.setText("Apartamento");

        menuItemNovoApartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/new_16.png"))); // NOI18N
        menuItemNovoApartamento.setText("Novo Apartamento");
        menuItemNovoApartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovoApartamentoActionPerformed(evt);
            }
        });
        menuApartamento.add(menuItemNovoApartamento);

        menuItemVerApartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/det_16.png"))); // NOI18N
        menuItemVerApartamento.setText("Ver Apartamento");
        menuItemVerApartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVerApartamentoActionPerformed(evt);
            }
        });
        menuApartamento.add(menuItemVerApartamento);

        menu.add(menuApartamento);

        menuInquilino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/inq_16.png"))); // NOI18N
        menuInquilino.setText("Inquilino");

        menuItemNovoInquilino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/new_16.png"))); // NOI18N
        menuItemNovoInquilino.setText("Novo Inquilino");
        menuItemNovoInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovoInquilinoActionPerformed(evt);
            }
        });
        menuInquilino.add(menuItemNovoInquilino);

        menuItemVerInquilino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/det_16.png"))); // NOI18N
        menuItemVerInquilino.setText("Ver inquilino");
        menuInquilino.add(menuItemVerInquilino);

        menu.add(menuInquilino);

        menuPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/cash_16.png"))); // NOI18N
        menuPagamento.setText("Pagamento");

        menuItemNovoPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/new_16.png"))); // NOI18N
        menuItemNovoPagamento.setText("Novo Pagamento");
        menuItemNovoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovoPagamentoActionPerformed(evt);
            }
        });
        menuPagamento.add(menuItemNovoPagamento);

        menuItemVerPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/det_16.png"))); // NOI18N
        menuItemVerPagamento.setText("Ver Pagamento");
        menuPagamento.add(menuItemVerPagamento);

        menu.add(menuPagamento);

        menuSenhorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/own_16.png"))); // NOI18N
        menuSenhorio.setText("Senhorio");

        menuItemNovoSenhorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/new_16.png"))); // NOI18N
        menuItemNovoSenhorio.setText("Novo Senhorio");
        menuItemNovoSenhorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovoSenhorioActionPerformed(evt);
            }
        });
        menuSenhorio.add(menuItemNovoSenhorio);

        menuItemVerSenhorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/det_16.png"))); // NOI18N
        menuItemVerSenhorio.setText("Ver Senhorio");
        menuSenhorio.add(menuItemVerSenhorio);

        menu.add(menuSenhorio);

        menuUtilizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/user_16.png"))); // NOI18N
        menuUtilizador.setText("Utilizador");

        menuItemNovoUtilizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/new_16.png"))); // NOI18N
        menuItemNovoUtilizador.setText("Novo Utilizador");
        menuItemNovoUtilizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovoUtilizadorActionPerformed(evt);
            }
        });
        menuUtilizador.add(menuItemNovoUtilizador);

        menuItemVerUtilizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/det_16.png"))); // NOI18N
        menuItemVerUtilizador.setText("Ver Utilizador");
        menuUtilizador.add(menuItemVerUtilizador);

        menu.add(menuUtilizador);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/close_16.png"))); // NOI18N
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem1);

        jMenuBar1.add(menu);

        menuAbout.setText("Sobre");

        menuItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cesar/renda/view/icon/info_16.png"))); // NOI18N
        menuItemAbout.setText("Sobre");
        menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutActionPerformed(evt);
            }
        });
        menuAbout.add(menuItemAbout);

        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        // TODO add your handling code here:
        new About(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemAboutActionPerformed

    private void menuItemVerApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVerApartamentoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuItemVerApartamentoActionPerformed

    private void menuItemNovoUtilizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovoUtilizadorActionPerformed
        // TODO add your handling code here:
        SwingUtils.addInternalFrame(desktop, new UserNew());
    }//GEN-LAST:event_menuItemNovoUtilizadorActionPerformed

    private void menuDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDashboardActionPerformed
        
        SwingUtils.addInternalFrame(desktop, new Dashboard());
    }//GEN-LAST:event_menuDashboardActionPerformed

    private void menuItemNovoApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovoApartamentoActionPerformed
        
        SwingUtils.addInternalFrame(desktop, new ApartamentoNew());
    }//GEN-LAST:event_menuItemNovoApartamentoActionPerformed

    private void menuItemNovoSenhorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovoSenhorioActionPerformed
        // TODO add your handling code here:
        SwingUtils.addInternalFrame(desktop, new SenhorioNew());
    }//GEN-LAST:event_menuItemNovoSenhorioActionPerformed

    private void menuItemNovoInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovoInquilinoActionPerformed
        // TODO add your handling code here:
        SwingUtils.addInternalFrame(desktop, new InquilinoNew());
    }//GEN-LAST:event_menuItemNovoInquilinoActionPerformed

    private void menuItemNovoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovoPagamentoActionPerformed
        // TODO add your handling code here:
        SwingUtils.addInternalFrame(desktop, new PagamentoNew());
    }//GEN-LAST:event_menuItemNovoPagamentoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Renda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Renda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Renda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Renda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Renda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menu;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuApartamento;
    private javax.swing.JMenuItem menuDashboard;
    private javax.swing.JMenu menuInquilino;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemNovoApartamento;
    private javax.swing.JMenuItem menuItemNovoInquilino;
    private javax.swing.JMenuItem menuItemNovoPagamento;
    private javax.swing.JMenuItem menuItemNovoSenhorio;
    private javax.swing.JMenuItem menuItemNovoUtilizador;
    private javax.swing.JMenuItem menuItemVerApartamento;
    private javax.swing.JMenuItem menuItemVerInquilino;
    private javax.swing.JMenuItem menuItemVerPagamento;
    private javax.swing.JMenuItem menuItemVerSenhorio;
    private javax.swing.JMenuItem menuItemVerUtilizador;
    private javax.swing.JMenu menuPagamento;
    private javax.swing.JMenu menuSenhorio;
    private javax.swing.JMenu menuUtilizador;
    // End of variables declaration//GEN-END:variables
}
