/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cesar.utils;

/**
 *
 * @author User
 */
public class Config {

//    public static final String DATABASE_NAME = "renda";
//    public static final String DATABASE_USER = "cesar";
//    public static final String DATABASE_PASSWORD = "cesar1234";
    public static final String DATABASE_NAME = "renda_pai";
    public static final String DATABASE_USER = "mario";
    public static final String DATABASE_PASSWORD = "mario123";
    public static final String DATABASE_DRIVER_OPEN = "jdbc:derby:" + DATABASE_NAME + ";create=true";
    public static final String DATABASE_DRIVER_CLOSE = "jdbc:derby:" + DATABASE_NAME + ";shutdown=true";
    public static final String DATABASE_CLASS = "org.apache.derby.jdbc.EmbeddedDriver";

    public static final String DATABASE_CREATION_SQL
            = "-- ALTER TABLE DROP  PRIMARY KEY id; \n"
            + "-- ALTER TABLE CESAR.apartamento DROP COLUMN id ;\n"
            + "-- \n"
            + "-- ALTER TABLE CESAR.apartamento ADD COLUMN \n"
            + "-- id INTEGER PRIMARY KEY NOT NULL \n"
            + "-- GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1);\n"
            + "-- CONSTRAINT id PRIMARY KEY (id);\n"
            + "-- ALTER TABLE CESAR.apartamento ALTER id SET INCREMENT BY 1;\n"
            + "-- \n"
            + "-- ALTER TABLE CESAR.apartamento \n"
            + "-- ALTER id INTEGER NOT NULL \n"
            + "-- GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1);\n"
            + "\n"
            + "CREATE TABLE apartamento\n"
            + "(    \n"
            + "    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,   \n"
            + "    num_quarto INTEGER,     \n"
            + "    area VARCHAR(50),\n"
            + "    piso VARCHAR(50),\n"
            + "    tipo VARCHAR(250),\n"
            + "    descricao VARCHAR(50),\n"
            + "    ref_quarto INTEGER UNIQUE\n"
            + "--     CONSTRAINT apartamento_pk PRIMARY KEY (id)\n"
            + ");\n"
            + "\n"
            + "CREATE TABLE contrato\n"
            + "(    \n"
            + "    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, \n"
            + "    data_assinatura DATE,\n"
            + "    data_termino DATE,\n"
            + "    data_vencimento_renda DATE,\n"
            + "    id_apartamento INTEGER,\n"
            + "    id_inquilino INTEGER,\n"
            + "    id_senhorio INTEGER,\n"
            + "    termos VARCHAR(500)\n"
            + "--     CONSTRAINT contrato_pk PRIMARY KEY (id)\n"
            + ");\n"
            + "-- CREATE TABLE contrato\n"
            + "-- (    \n"
            + "--     id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),\n"
            + "--     data_assinatura DATE,\n"
            + "--     data_termino DATE,\n"
            + "--     data_vencimento_renda DATE,\n"
            + "--     id_apartamento INTEGER,\n"
            + "--     id_inquilino INTEGER,\n"
            + "--     id_senhorio INTEGER,\n"
            + "--     termos VARCHAR(500),\n"
            + "--     CONSTRAINT contrato_pk PRIMARY KEY (id)\n"
            + "-- );\n"
            + "\n"
            + "CREATE TABLE inquilino\n"
            + "(    \n"
            + "    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,\n"
            + "    nome VARCHAR(50),\n"
            + "    sexo VARCHAR(50),\n"
            + "    data_nascimento DATE,\n"
            + "    doc_identicicacao VARCHAR(50),\n"
            + "    num_documento VARCHAR(50),\n"
            + "    nacionalidade VARCHAR(50),\n"
            + "    contato VARCHAR(50)\n"
            + "--     CONSTRAINT inquilino_pk PRIMARY KEY (id)\n"
            + ");\n"
            + "\n"
            + "CREATE TABLE pagamento\n"
            + "(    \n"
            + "    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,\n"
            + "    data_pagamento DATE,\n"
            + "    valor_pago REAL,\n"
            + "    pagamento_mês VARCHAR(50),\n"
            + "    pagamento_ano VARCHAR(50),\n"
            + "    id_contrato INTEGER,\n"
            + "    id_inquilino INTEGER\n"
            + "--     CONSTRAINT pagamento_pk PRIMARY KEY (id)\n"
            + ");\n"
            + "\n"
            + "CREATE TABLE senhorio\n"
            + "(    \n"
            + "    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,\n"
            + "    nome VARCHAR(50),\n"
            + "    sexo VARCHAR(50),\n"
            + "    data_nascimento DATE,\n"
            + "    doc_identicicacao VARCHAR(50),\n"
            + "    num_documento VARCHAR(50),\n"
            + "    nacionalidade VARCHAR(50),\n"
            + "    contato VARCHAR(50)\n"
            + "--     CONSTRAINT senhorio_pk PRIMARY KEY (id)\n"
            + ");\n"
            + "\n"
            + "CREATE TABLE users\n"
            + "(    \n"
            + "    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,\n"
            + "    fullname VARCHAR(50),\n"
            + "    username VARCHAR(50),\n"
            + "    password VARCHAR(50),\n"
            + "    user_type INTEGER\n"
            + "--     CONSTRAINT users_pk PRIMARY KEY (id)\n"
            + ");\n"
            + "";
}
